wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1701082093.065071
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 35
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 2
      - 23
      4: 3.11.4
      5: 0.15.12
      6: 4.35.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
